### ISSUE TITLE
Vyre Thieving Issue

### ISSUE THREAD

**Issue by JoshTheBaker** [oldschoolgg/oldschoolbot#1618]
![Vyre issue](https://user-images.githubusercontent.com/77371283/113128920-51751580-91e8-11eb-856d-fde9c6c0b2ea.png)

The chance of a successful pickpocket without boosts is 42% at level 85 and 50.196% at level 99. This increases by 10% if the Thieving cape is worn and by another 10% with the completion of the hard Ardougne Diary, making the highest possible success rate 60.7%. A successful pickpocket yields coins or other items and 306.9 Thieving experience. 

(The thieving level that I am doing Vyre's at in the screenshot is 99)

**Comment by HouseParan73** [comment]
Assuming you have your thieving cape equipped then the only issue in seeing is that ardy diary perk isn't a thing yet on the bot (which is why master farmers can't be 100% successful without the cape at 99). The wiki rate of successful pickpockets can't just be applied to the return message on the bot since the return message of 2000 pickpockets is just based on the amount of time your trip took. The 2000 would only be possible assuming 100% success rate. Given the high fail rate of vyres, you're getting stunned often and each time you're stunned you're losing out on multiple attempts to pickpocket. 

Your rate comes out to around 166k/hr and in game you won't get higher than 220k/hr longterm, so it might be a little off but it shouldn't be 1000 successful pickpockets in a 40 min period or else vyres would be meta by a lot in the real game

**Comment by Lajnux** [comment]
resolved
