### ISSUE TITLE
Better Dungeoneering Experience

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#1694]
Currently Dungeoneering is a hot skill to train, but for BSO standards it's super slow and could use some improvements (based on player experience).

1. Increase xp gained at Floor 6, with like 180k xp a trip, it will take you about 500 trips (290+ hours) to get to Floor 7. At like half that rate, it's still a lot but more doable.
2. Increase the droprate of Gorajan Shards (not sure where it is now), to either have a higher droprate at higher Floors or a general higher droprate. Because the Gorajan sets increase xp, but at current rates it's basically impossible to get a full set without having to buy most of em.
3. To add to that, maybe at the Gorajan Shards to =dg buy for 1m points (1 buyable shard every 10m xp, seems reasonable)

Lots of Love,
A lot of Dungeoneers

**Comment by slippy3** [comment]
At the current shard rate it will take just under 1000 hours on average to get 30 shards. At that rate the set Is essentially useless as you won't be able to use it for the boost. 
Wholeheartedly agree with the above suggestions. 

Floor 1-6 xp is quite slow for bso standards and the shards shouldn't be that hard to obtain/rates need to increase as you go to higher floors. 
Also adding the shards to the dg shop would make tokens useful if you plan on going for high xp, otherwise you have nothing to spend tokens on once you've bought everything.

In game you can buy dg xp with tokens as well, that would also be another decent way to spend tokens once you've bought everything.

**Comment by jesseman1121** [comment]
I support and agree with everything mentioned above. The grind to 99 was nice and fun with others but at floor 6 it feels more like a punishment and too much of a grind for BSO.

**Comment by taco-69** [comment]
In support of adding Gorajan shards to dungeoneering reward shop:

Shard rate 1/2000 minutes (1/33 hrs) after F5 with no rate increase

Assuming this rate, on average will take ~990 hours of DG to complete Gorajan armor sets (~1980 trips total)



Adding Gorajan shard to DG shop at a price of 1m tokens / shard would add 1 shard per ~37 trips at

~270k xp / trip, ~30 minutes per trip, ~27k tokens per trip (assuming no personal Gorajan bonuses - F6 xp/token rates)



1 shard / 37 trips (bought)

1 shard / 66 trips (dropped)

~726 trips to reach 30 Gorajan shards needed for full sets with a 1m / shard sink in token shop.

Adding Gorajan shards to shop would save people around 627 hours trying to get all 3 Gorajan sets.

**Comment by gc** [comment]
Added a couple buffs to dg xp.
