### ISSUE TITLE
CoX

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1747]
Equipping twisted buckler takes gear score from 98.8% —> 83%

Book of law was equipped previously

**Comment by Paah** [comment]
It's because the buckler pushes your stab/slash/crush attacks to negatives.  The bis setup for example has 4 slash attack so getting -8 from the buckler essentially gives you -200% stats. Multiply by the 3 stats for -600%. So now you are not only missing 3 stats but also negating 6 others.

Some solutions could be limiting bonus from a stat to [0,100] so it can't go into negatives, or not checking irrelevant stats for gear setups, like melee accuracies for range setup.

**Comment by ahmalla** [comment]
Hmm yeah I see.. not exactly easy to replicate a “switch” scenario I suppose. 
Unfortunate cause it should be an upgrade
