### ISSUE TITLE
Alchemical Hydra doesn't drop leather

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2114]
## 🐛 Bug Report

As the title says. Simulation command does not show hydra leather as a drop (unless im blind)
![hyseDDsd](https://user-images.githubusercontent.com/63373565/122611497-6a56cf80-d04f-11eb-9c2d-ba9c81a87959.png)

**Comment by JoeMilian** [comment]
Hey @mylife212,

The issue was fixed by @themrrobert in the following pull request https://github.com/oldschoolgg/oldschooljs/pull/191 which was merged 17 days ago. Thank you for reporting the issue, if you can still reproduce the issue please make a comment if not please close the issue.

Thank you again.

**Comment by mylife212** [comment]
Hello @JoeMilian, 

Thank you for the resport and the update, i am glad it xcgot merged  ! i aprurecite the update and it has not been able to bee resolved so i wuiol clos ethe issue now. i ope you have a great and uappy day, I I WILL clos eth eissues as per yoyurj request, joeMillian. I apprweciate ther u p p pewpwpw pp p p p p p .  Thanks!!

may Hammy bless you,
Mylife212.
