### ISSUE TITLE
AD Claim Dupe Lamp

### ISSUE THREAD

**Issue by ReignsAbove** [oldschoolgg/oldschoolbot#2485]
## 🐛 Bug Report

In BSO (haven’t tried in OSB) if you sell your achievement diary item and claim the diary again to get the item back, you get a xp lamp as well. Only stumbled upon it because someone had an item contract for Varrock armour 3. I traded him the item, then went to claim to get armour back and the lamp came with it.

**Comment by animelewds** [comment]
I may be wrong but claiming the same diary will give you a lamp for other unclaimed diaries. If you've done Fally easy and Varrock easy you're owed 2 easy lamps. So if both are unclaimed, by claiming Varrock twice, youll recive 1 lamp for Varrock and the second for Fally. If you went to claim fally after the second time, you wont receive a third lamp since you already claimed them through Varrock. This applies to every tier and every diary.

**Comment by ReignsAbove** [comment]
Interesting, you’re right. So I dropped a 15k xp lamp for nothing. Didn’t want to use what I thought was duped lamp xp.
