### ISSUE TITLE
Drift net fishing XP/hr 

### ISSUE THREAD

**Issue by TitanGH** [oldschoolgg/oldschoolbot#3051]
## 🐛 Bug Report

Drift net fishing XP seems to be calculated wrong. On a trip using 68 drift nets and shelldon I got 404k xp, but it should have been around 538k xp with my fishing level and boosts. The average xp per net used is 769, doubled for shelldon then 5x for bso comes to 7690 fishing xp and 5088 hunter xp per net.

**Comment by TitanGH** [comment]
Bump, the XP/hr is off of what it should be even more now.

**Comment by TitanGH** [comment]
Bump

**Comment by TitanGH** [comment]
Bump

**Comment by TitanGH** [comment]
🧐

**Comment by Lajnux** [comment]
Shelldon doesn't affect drift net fishing same way as angler fishing set doesn't affect it. (for BSO who knows what will come in future)

Also base xp for driftnet is 720 hunter xp and 565 fishing xp. then there is added xp ontop of this depending on your hunter/fishing level scales up to lvl 70s.

The hunter xp will be around 1015 xp/net (OSB), the fishing xp I'm too lazy to calculate.

**Comment by TitanGH** [comment]
The figures I gave were with the maximum scale and calculated carefully, knowing the angler outfit doesn’t work for drift nets. As someone who has done a lot of drift net fishing in game I can say there should not be as bug of a swing as there currently is. There should also be a buff for experience in the activity because you become more efficient once you learn how the fish move.

**Comment by Lajnux** [comment]
There is no figures provided in this issue that I can see.

Since you didn't trust me first time here is some math.

Each drift net gives 1015 hunter xp and 775 fishing xp. You average 119 drift nets per hour with maximum boosts (fishing level, hunter level 70+, flippers and stamina potion and ring of endurance).

119 x 1015 hunter xp = 120.8 k hunter xp/hour
119 x 775 fishing xp = 92.2 k fishing xp/hour
Below is a image of the wiki page for drift net fishing in OSRS. As you can see the xp/rates in the bot is higher than the wiki page this is because the wiki page normally considers a slightly slower xp/hour because people are not as efficient. Let me know if you accept this as a answer so I can close this issue. 
![Screenshot_20211208-173735_Chrome](https://user-images.githubusercontent.com/68188574/145247197-2613ae85-a721-455e-a6cd-c4740d77cf29.jpg)

**Comment by TitanGH** [comment]
Yes, but using the numbers you just provided the fishing xp/hr on bso using Shelldon should be 922k, but it’s less than 800k. And the fact still remains that there should be some sort of experience buff for the activity, like almost everything else.

**Comment by Lajnux** [comment]
I already said Shelldon doesn't provide boot for driftnet activity since it's a hunter/fishing method. Same way as Sandy isn't providing a boost to it either. Sure drift net could get some love and new features for BSO. But then I would suggest you to write a suggestion rather than a issue. Because you now agree drift net is right balanced from what I posted. And the information I gave you is also visible in the code. 
Case closed.
