### ISSUE TITLE
[BSO] Remove the chance of getting 3a Item contracts from last update

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3114]
## 🚀 Feature Proposal

Title. 

It is simply a slap in the face for players with higher streaks, as they now have a chance to get an expensive IC for absolutely no reason. It only punishes those with higher streaks and encourages skipping contracts+ruining streaks to avoid this happening.

 Even if I got it wrong - and higher streaks is less chance of getting a 3rd age IC - there is still NO reason why the player should have a chance of an arbitrarily expensive contract for the same reward as anything else. In fact, it should be a very rare chance of getting any (one) 3rd age item from an IC reward at a higher streak to encourage players to maintain higher streaks.

**Comment by themrrobert** [comment]
I tend to agree. The rewards from item contracts are frankly not good enough to justify this.

I think the item contracts are a decent idea, but they don't really do well as an item sink because even the small rewards they give usually outweigh the items going in, but the rewards aren't good enough to justify sacrificing larger items with **any** sort of regularity unless you really care about that streak, which is a limited number of players.

This change could be the final nail in the coffin for those players that do occasionally sacrifice high value items. 

Might be worth seeing how it pans out though, people are inherently hard to predict.

**Comment by mylife212** [comment]
Exactly how I feel too, item contracts are meant to be a small fun side thing and not an item sink for valuable items.

> This change could be the final nail in the coffin for those players that do occasionally sacrifice high value items.
Especially agree with this though. As someone who was maintaining a high streak, and was happy to sac the occasional 3a here or there, I cant be bothered anymore if it's going to be constant forced high value sacrifices for literally no extra reward.
