### ISSUE TITLE
[OSB] Tokkul shop

### ISSUE THREAD

**Issue by FatOrangeKitty** [oldschoolgg/oldschoolbot#3338]
I can see a couple of lines that should prevent the user from buying and selling items to the tokkul shop if they have not defeated Jad, however, I have tested this with a new user and he can do both with 0 Jad kills.

Also, upon use of the `+tokkulshop buy (incorrect item spelling)`, it gives the message of:

> I don't recognize that item JalYt, here are my wares: Tin ore, Copper ore, Iron ore, Silver ore, Coal, Gold ore, Mithril ore, Adamantite ore, Runite ore, Uncut sapphire, Uncut emerald, Uncut ruby, Uncut diamond, Uncut dragonstone, Uncut onyx, Onyx bolt tips, Obsidian throwing ring, Obsidian sword, Obsidian dagger, Obsidian maul, Obsidian staff, Obsidian mace, Obsidian cape, Obsidian shield, Obsidian helmet, Obsidian platebody, Obsidian platelegs, Fire rune, Water rune, Air rune, Earth rune, Mind rune, Body rune, Chaos rune, Death rune.

However, you cannot buy several of these items. They are:
- Silver ore
- Coal
- Gold ore, 
- Mithril ore
- Adamantite ore
- Runite ore
- Uncut ruby
- Uncut diamond
- Uncut dragonstone

When typing in the cmd of `+tokkulshop buy (one of the items you cannot buy)`, it gives you the correct error message of:

> I am sorry JalYt, but I can't sell you that. Here are the items I can sell: Tin ore, Copper ore, Iron ore, Uncut sapphire, Uncut emerald, Uncut onyx, Onyx bolt tips, Obsidian throwing ring, Obsidian sword, Obsidian dagger, Obsidian maul, Obsidian staff, Obsidian mace, Obsidian cape, Obsidian shield, Obsidian helmet, Obsidian platebody, Obsidian platelegs, Fire rune, Water rune, Air rune, Earth rune, Mind rune, Body rune, Chaos rune, Death rune.

**Comment by LuxrayElite** [comment]
The items limited by jad kills are obsidian armour which requires inner city/inferno access. Because we don't have inner city shops access buy variables are optional, general tzhaar shops can buy those items from you but don't actually stock it

I did plan on updating tks for inner city shops but shops need to be coded as trips to prevent buying mass runite ore for example.

Reference #3177 (I think that's the pr for making them buyables) on mobile
