### ISSUE TITLE
ignore cooldown on +m button presses

### ISSUE THREAD

**Issue by Wes1239** [oldschoolgg/oldschoolbot#3534]
## 🐛 Bug Report
Button presses on +m only work if you wait a few seconds to press the button

https://puu.sh/IHYsv/c728c77db8.mp4

**Comment by Wes1239** [comment]
It started today and happens on both bots.

**Comment by AvariceBrah** [comment]
Can you try this with another command that yields buttons?

 There's a chance it could be rate limiting that's causing this but it usually yields a return message (as if you failed a 
slash command due to string error) that only you can see.  

If you can find another situation of this occuring, post it as well.

**Comment by Wes1239** [comment]
Did some more testing
Don't work: repeat MonsterKilling, KalphiteKing, Wintertodt, MahoganyHomes, Crafting, Fletching, Construction, Firemaking, 

Do work: luckypick, sell/drop confirmations, clue buttons including repeat ClueCompletion

**Comment by gc** [comment]
Closing as an old issue, feel free to re-open if this is still a problem.
