### ISSUE TITLE
Cant create godsword blade

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3692]
Theblokeman#7101 / 346161766079660032 is unable to create godsword blades

Command and create works fine for everyone else but throws an error for him, not a clue why

![0964221C-D42C-4F4E-8CA0-04B3AEB1E64E](https://user-images.githubusercontent.com/76587427/159171215-65339afc-8f5b-427e-80d4-00a83fcd31ad.png)

![8FDF9775-6275-4D07-9E1B-45EE9113FF14](https://user-images.githubusercontent.com/76587427/159171256-907a60dd-fe9e-470e-8927-fa23744a0ac1.jpeg)

**Comment by themrrobert** [comment]
This is the same issue we've seen a few times now, where a player comes back after a long period of time.

Something in the old code only set items to quantity = 0, instead of deleting the entry.

The bank code always expects there to be at least 1 if the item is in the db, which is why it shows '1' but really there's 0 there.

Replacing the item is the only way to solve this without a datafixer update.
