### ISSUE TITLE
[Feature Proposal] Hill Giants

### ISSUE THREAD

**Issue by Incompet3nt** [oldschoolgg/oldschoolbot#377]
Could Hill Giants please be added to the kill simulator, and things to be killed by a minion?
They are a nice source of low/mid lvl seeds, and could help when/if the Farming skill is added. They're also another source of Giant Champion scrolls, for the collection log.

I'm not sure what other details I ought to add, so hopefully this is enough.

**Comment by eX-C0n** [comment]
+1, although, the seed drops are _quite_ rare for such an easy monster. 
In addition to adding hill giants though, we should also add Obor! Since the Giant Key is on the hill giant's drop table. Obor would definitely have a KC competition since it would have a 1key=1kc requirement :P
`It is consumed when used to unlock the gate, allowing one Obor fight per key. It is possible to hold more than one Giant Key at once.`

**Comment by Alexsuperfly** [comment]
To any devs looking to make this, [OldschoolJS](https://github.com/oldschoolgg/oldschooljs) is where we host all the LootTables for monsters.  the hill giant would go in [monsters/low](https://github.com/oldschoolgg/oldschooljs/tree/master/src/simulation/monsters/low) and Obor in [monsters/bosses](https://github.com/oldschoolgg/oldschooljs/tree/master/src/simulation/monsters/bosses).  
The bot only needs an entry into [killableMonsters](https://github.com/oldschoolgg/oldschoolbot/blob/dev/src/lib/minions/data/killableMonsters/index.ts) for the bosses, key consumption would have to be handled on additionally in some new way perhaps with a `consumedItem?` field on the [KillableMonster type](https://github.com/oldschoolgg/oldschoolbot/blob/dev/src/lib/minions/types.ts#L40)

**Comment by coolbop32** [comment]
feature is now in bot
