### ISSUE TITLE
Update the 3rd age rate of Elite reward caskets, to match in-game.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3989]
## 🚀 Feature Proposal

Elite clues in OSRS were bugged and had an exponentially higher chance of 3rd age compared to other tiers. In a recent update, this got fixed and its now **a 1/13750 chance per roll to get 3rd age**. 

I believe this is being delayed as we dont know what happened to gilded rate as a result - but IMO it shouldn't be an issue. Looking at other Casket gilded rates, its (per roll!) : 1/3250 - Hards, 1/2053 - Elites and 1/1316 - Masters. Meaning the Gilded rate fits perfectly with the other tiers, so it shouldn't be an issue.

**Comment by osDreamscape** [comment]
![image](https://user-images.githubusercontent.com/73551894/172789843-703606ca-8243-4e4a-96eb-4a6abb51a4fa.png)
adding an extra 3a roll to the MR table almost exactly matches what changes to rates jagex did, without them providing their actual data (still nothing from jagex as of yet regarding the actual new tables), current 3a rates from elites ingame ARE 1/2750. On the bot they are 1/5750, as it still has old rates. Without modifying any other tables or doing anything too fucky, adding an additional 3a roll on the MR table brings 3a rates to 1/3k instead of the 1/5750, and only negatively effects gilded rates as a byproduct by ~3%

**Comment by mylife212** [comment]
Dreamscape was correct - This is how its officially implemented in the game. https://twitter.com/JagexAsh/status/1529773495588208641

**Comment by J4stMart** [comment]
Yeah, so that answer from Ash doesn't really make sense. Because if you add an entry to the rare table (50 to 51), the full mega rare table would get a buff instead of only 3rd age.

I'd assume ash made a mistake here, and meant to add an entry to the mega rare table instead (23 to 24). Which would make the 3rd age rate 2/24, equal to dream's 1/12.

**Comment by Redquaker** [comment]
Agreed that the answer doesn't make sense. Shifting 3rd age to 2/24 rolls isn't really ideal either though since it's still not consistent with the actual rate in OSRS (1/2,750 per clue or 1/13,750 per roll).

Question 1 states the actual rate: https://oldschool.runescape.wiki/w/Poll:Old_School_Content_Poll_76:_Game_Improvements

I guess a intermediate buff to 1/15,000 per roll is better than nothing, but it'd still be good to find out the real numbers.

**Comment by J4stMart** [comment]
A wiki admin confirmed that it is indeed the buff Ash mentions in his tweet. The runelite drop rate crowd sourcing confirms the buff in the full mega rare table. [Link](https://www.reddit.com/r/2007scape/comments/v9ak6t/the_buff_to_elite_clue_3rd_age_drop_rates_also/)

**Comment by gc** [comment]
Done
