### ISSUE TITLE
Minion Tiers

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#425]
## 🚀 Feature Proposal

The general idea is...
- There's 5~ minion tiers, from t1 to t5 (no relation at all to patreon)
- You start at tier 1
- To advance in a tier, you need to reach certain achievements, for example you might need base 50 in all skills, 50 QP, 500m sacrificed.
- Each tier will provide benefits/perks, with some patron perks being given access from higher minion tiers. As well as any other benefits/perks we can think of, including the different minion icon. 
- Benefits: more reasons to train skills and sacrifice (item sinks, economy stimulation), gives ability to unlock patron perks without having to pay.

**Comment by kevinsmendes** [comment]
**yellow** : 1% trip bonus
**green**  : 2% trip bonus, +sell now are 85% of the item value, instead of 80%.
**purple** : 3% trip bonus, +1 minutes trips, access to C and O commands (C already exists and are a T1 perk, it'll also be a T1 perk, but be linked with sacrifice now aswel. O would be a new command that allows you to automatically open the clue upon return).
**blue**   : 5% trip bonus, +5 minutes trips, Access to Open multiple (It would need to be developed, but a `+open [number] item` would give access to the user to open multiple items at once (like, `+open 100 crystal chest`, 100 keys would be used at once)
**white**  : 10% trip bonus, +10 minute trips, +sell now are 90% of the item value, instead of 80%. Possible chance to receive 10% more loot (Rounded Down) or XP from a trip (1% chance).

Trip bonus is the same as the 10% we can get by expensind 50 hours killing a monster. I thought 1 minute per bil sac is an OK number. In my mind, this should NOT affect masses.

**Comment by osrsolympus** [comment]
Bump
