### ISSUE TITLE
Gear presets

### ISSUE THREAD

**Issue by TitanGH** [oldschoolgg/oldschoolbot#4411]
## 🐛 Bug Report

Gear presets are currently unable to be edited since to the transition to slash commands, this is a necessary feature that needs to be fixed.
With all the new gear recently added everyone’s presets are going to change slightly and shouldn’t have to be remade.

**Comment by TURB042O** [comment]
I have been frustrated with this myself having to delete and create everytime I wanna update a preset.

otherwise it'll just remove all the gear in the preset or remove all except the change you made. 


in order to use `/gearpresets edit` we have to type everything including what's already equipped

**Comment by TURB042O** [comment]
> I have been frustrated with this myself having to delete and create everytime I wanna update a preset.
> 
> otherwise it'll just remove all the gear in the preset or remove all except the change you made. 
> 
> 
> in order to use `/gearpresets edit` we have to type everything including what's already equipped 

I'm with you on this one man I have even said something but look a year later no change smh

**Comment by nwjgit** [comment]
`/gearpresets edit gear_preset:`
