### ISSUE TITLE
Boost for Thammaron's sceptre 

### ISSUE THREAD

**Issue by 2Kurrupted** [oldschoolgg/oldschoolbot#4451]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

Add some form of boost to wildy monster kills when using a Thammaron's sceptre please? Currently Thammaron's sceptre has no boost despite being able to be charged and reverted in the bot, also both Craw's bow and Viggora's chainmace have their boosts counted towards respective bosses etc leaving Thammaron short. Amulet of Avarice also has no boost however I understand why this would be the case in relation to OSRS.  
Cheers

**Comment by mylife212** [comment]
As much as I agree with you, the sceptre also has literally no use ingame from what I understand. Even the crazy archaelogist setup on wiki (Only place you'd realistically use it) places it between ibans staff and normal trident

It is worth noting there will be a buff for sceptre coming with wildy boss rework iirc, so that has potential

**Comment by 2Kurrupted** [comment]
Ah okay makes sense :) thanks
