### ISSUE TITLE
BSO spawn lamp/box change

### ISSUE THREAD

**Issue by Brane-Ded** [oldschoolgg/oldschoolbot#4659]
## 🚀 Feature Proposal

Im not sure of a way to resolve this issue, but it is highly irritating. bso spawn lamps is absolutely infuriating, every time I try to spawn a lamp or a box, with the command that I got from PAYING on patron, someone will spam any button to try and steal it. its a paid perk, why would anyone else be able to steal your stuff? you ran the command, you paid the patron tier price, why would anyone be able to interact with your command? ive heard this is about not wanting people to have a lamp 100% of the time, thats fine. make it a 33% chance to get something, idc. but dont let someone RUIN someone elses PATRON PERK. i paid to support magna, and the lamp is part of the package. why can others steal it from me and harass me about it? I dont want to be forced to go to the MOST POPULAR bso channel to use the command. NO ONE should be able to interact with a paid command, that they DIDNT pay for. how are non patrons benefiting from patron perks?

1. Let spawn box and spawn lamp be used on other channels, dont force it on the most populated channel.
2. Dont let non patrons interact with patron commands
3. Implement different ways of limiting lamps/boxes (if thats the issue about it), other than letting others grief people.
4. If no to all 3, then let ironmen have a few secs of immunity to other peoples griefing. (give irons ~5sec before others can steal your patron perk) especially cause they are perm irons, getting a 100% lamp or box isnt going to break the game.

to me, this is 100% a problem.

**Comment by Lajnux** [comment]
I would love to see this topic discussed in the #bso-discussion channel

**Comment by Lajnux** [comment]
> I would love to see this topic discussed in the #bso-discussion channel

Made a BSO-discussion on the topic, there is multiple stances and there clearly is something that affects players in a negative way but most are passive accepting it because of tradition, linking the discussion below:
https://discord.com/channels/342983479501389826/1016008399500091432/1036306446456979499

**Comment by gc** [comment]
I understand the annoyance you have - the reason it's like this though, is to reduce the "P2W"-ness of it. The perk of being a patron is to spawn it, not to get it. We made a change to make it easier for the patron to get (they get 2 guesses instead of 1). I'm open to more changes, like: the spawner gets the first guess OR the first X seconds, and then others can guess. I'm closing this and making a poll in the bso vote channel.
