### ISSUE TITLE
+finish [Beginner/Easy/Medium/Hard/Master/Elite]

### ISSUE THREAD

**Issue by CTFries** [oldschoolgg/oldschoolbot#472]
## 🚀 Feature Proposal
Add clues to the ```+finish``` command. 

Maybe use a flag to either show clue shared or ignore clue shared.

**Comment by Alexsuperfly** [comment]
finishing clues takes upwards of 100-200k iterations since their clue tables are so large and so sparse, i dont believe this would be a good idea for the health of the computing power of the bot.  However i could see this maybe being a patreon command to limit the amount of people who could spam it can lock up the bot so im leaving it open specifically for that

**Comment by gc** [comment]
Done in next update https://github.com/oldschoolgg/oldschoolbot/pull/4628
