### ISSUE TITLE
maybe bug

### ISSUE THREAD

**Issue by englishfarms** [oldschoolgg/oldschoolbot#4782]
Hello, I’m not sure if this is a bug, but when I send a trip of clue runs for 5 GMC. If I click the repeat button after run, it will go with my max amount of 6 GMC per run instead of the 5 I was initially doing.

**Comment by hyperxbeast** [comment]
I've found this. But I think repeat trip will always send / return maximum on any trip unless you for instance had a boost activated prior which has since been disabled. I.e. clue hunter / graceful, then unequipping and repeating trip would result an unable to send trip message. Would be good to clarify though!

**Comment by DarkBugz** [comment]
Most trips do not automatically send a full trip on repeat. They repeat exactly what the previous trip was.
