### ISSUE TITLE
BSO Toa Void staff issues

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5140]
## 🐛 Bug Report

My iron ran out of charges on the void staff, easy fix equip kodai and move one. Then the bot wouldn't send the raid, it was a 4 man mass. Just "bso is loading" the entire time. Message never went away. All 4 minions remaining idle. Recharged the staff and re-equipping it fixed the problem. But having a charged void staff, and equipping a kodai want results in toa still charging you void staff charges even tho it's not equipped, and you don't recieve the boost from it either.

**Comment by ghosts-are-spooky** [comment]
Had something similar. Behaviour was:
Max host with 100% gear/boosts. Got the loading message as described above.
We did this a few times and then noticed:
1. It removed supplies (void staff charges, hellfire arrows etc.) each time the trip sent.
2. When we moved to a host that did not have the void staff, we were able to send the mass.

Seems it is due to the trip forcing all raid members to have the boosts of the leader, not sure if the trip from @bigsquid69 he was hosting then swapped weps, or simply somebody else with void was hosting.

Cyr checked errors and got following:

Error: Zatchary had missing Void staff when trying to degrade by 120

Error: Dondo had missing Void staff when trying to degrade by 90

These 2 players did not have a void staff equipped, nor owned at all

**Comment by bigsquid69** [comment]
I wasn't the host. I'm a main so charges are no issue. My iron also wasn't the host, the issue occured when the item "void staff (u)" was in possession, but even after it was recharged, and not equipped it used 30/ raid or 90/ trip since we have t3+yak as a host(not me). Hopefully this helps 🥺 but you're definitely on to something with it requiring everyone to have the same reqs as the hose. Kinda sucks because the iron is the leech and doesn't effect raid time anyway.. elders are limited resources for me 😭🤣

**Comment by gc** [comment]
Fixed in next update
