### ISSUE TITLE
[osb] Not recieveing Torva kit after 4x awakened bosses defeated

### ISSUE THREAD

**Issue by Lewis7777** [oldschoolgg/oldschoolbot#5285]
4 awakened bosses have been defeated, however the kit wasn't recieved.

the newspost states:
You now get a ancient blood ornament kit, upon killing a awakened boss, if you dont own one, and have killed all 4 awakened bosses.

Unsure if this means that's what you have to do to get your first kit? or if this is what happens if you sacrifice/lose your kit (this is what happens on osrs).
You should get the kit after you have defeated 4 awakened bosses, 1 of each.

**Comment by nwjgit** [comment]
The news post says it spot on how it works.
1kc on each awakened boss and no kit in bank, will give you a kit on the next awakened kill. 

You can read more about it here when we tested it yesterday: https://discord.com/channels/342983479501389826/1016008399500091432/1144442532827250829

It doesn't work 100% like it does ingame. Not sure if that was intentional or not.

**Comment by Lewis7777** [comment]
> The news post says it spot on how it works. 1kc on each awakened boss and no kit in bank, will give you a kit on the next awakened kill.
> 
> You can read more about it here when we tested it yesterday: https://discord.com/channels/342983479501389826/1016008399500091432/1144442532827250829
> 
> It doesn't work 100% like it does ingame. Not sure if that was intentional or not.

Weird, in testing at one point it would give u the kit if u did 4x awakened boss, then killed any 1x regular boss. this would be better if its difficult to code it the proper way.
