### ISSUE TITLE
Pet bug idk

### ISSUE THREAD

**Issue by muntaman** [oldschoolgg/oldschoolbot#543]
So i Got the 2 pet from 2 seperat boxes, b2b. And one of the pet is showcased on the cl pet, But the other one is not shown, so idk Maybe a bug
![CD8FC186-9830-423E-ACF0-75BC5E593382](https://user-images.githubusercontent.com/46559544/90984851-1fc40e00-e578-11ea-9928-fa5b9b3d407b.png)

**Comment by Lajnux** [comment]
The pet that you got have different IDs depending on which color you get. And as you might see on your picture your pet is bluish meanwhile the other one got a lighter colour. Probably yellowish/ light greenish. 

Since the cl log only take into account the ID of the right color. Your pet won't be registered in the collectionlog.

**Comment by Sethmare** [comment]
It looks like you got the blurite golem, but the collection log golem is the regular rock golem. I think the collection log only counts the default golem because that is always how it is obtained initially in the game. Everybody gets the brown one and can then recolor it from there. Since you bypassed obtaining the brown one, your collection log wouldn't register it to your collection log.![image](https://user-images.githubusercontent.com/66145237/91008014-9ffb6b00-e59a-11ea-8440-d60120f4c5b2.png)

**Comment by gc** [comment]
This is just one of those BSO things that we have to deal with because the fact you can get ANY item, stuff like this happens.
