### ISSUE TITLE
+Last command

### ISSUE THREAD

**Issue by deonm122** [oldschoolgg/oldschoolbot#572]
## 🚀 Feature Proposal

A simple request, a command that allows you to see the last loot from the last monster you kill again. Sometimes if you're playing in the bot-channel, the picture of your loot can get lost very quickly. And rather than having to scroll up and try to find your picture, the +last command would simply repost it for you.

**Comment by Lajnux** [comment]
rather than making a new command for seeing the last loot I would highlight that it's possible to DM the bot and do your commands in there and only use the dedicated bot channels for interacting with others by gambling, selling stuff or showing off stuff. You can still share your drops in this channel by just copying the generated image from the DM with bot. Private server also works.

Close issue.

**Comment by Lajnux** [comment]
this is not feasible to code, therefor closing.
