### ISSUE TITLE
Slayer task extend doesn't work on some wilderness slayer task + small wildy slayer naming issue.

### ISSUE THREAD

**Issue by Usvaaa** [oldschoolgg/oldschoolbot#5959]
Slayer task extend doesn't currently work on nechryael's and black dragons on tasks from Krystilia.

I also noticed that some slayer tasks are named incorrectly, although this might be intended. For example Krystilia is supposed to assign Bears, but on osb the task is called Grizzly Bear. The other example is Greater Nechryaels (the task is supposed to be Nechryaels). There might be others but I noticed these ones. The correct names are here https://oldschool.runescape.wiki/w/Krystilia

**Comment by TastyPumPum** [comment]
The extensions are fixed in #5958 

There is only greater nechryaels in the wilderness from what I can see, so although Krystilia might call it normal nechs in osrs you can only kill the greater nechs from what i can see.

Similarly bears is just an overall name jagex use but we have to assign it to an actual monster id and I believe Grizzly bears are the only bears in the wildy (except artio and callisto)
