### ISSUE TITLE
Woodcutting bug

### ISSUE THREAD

**Issue by Kyria-Dax** [oldschoolgg/oldschoolbot#6033]
I've experienced a bug in the woodcutting skill I've done a lot of wc and received no logs
![Screenshot_20240831_211104_Discord](https://github.com/user-attachments/assets/4f854e37-c4e5-4dfc-90f2-db8499db5dea)
![Screenshot_20240831_211104_Discord](https://github.com/user-attachments/assets/6b9cf61d-8bdb-40b4-a429-bb20d1bee54c)

**Comment by Kyria-Dax** [comment]
![Screenshot_20240831_211019_Discord](https://github.com/user-attachments/assets/67d9fc4b-a171-4949-8f61-ce8ed70fa39e)

**Comment by nwjgit** [comment]
- https://github.com/oldschoolgg/oldschoolbot/pull/6034 this corrects the `Your minion is now chopping Logs until your minion chopped 999999999999999x or gets tired` issue.
- I imagine you're not receiving logs because you are powerchopping. That means your minion is "dropping" the logs to receive a higher xp rate.
