### ISSUE TITLE
OSB Amascut's Remnant CA

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#6057]
It appears that after the recent CA fix, the Amascut's remnant CA is still not being given.
![Screenshot_20240918_232053_Discord](https://github.com/user-attachments/assets/5dd2c357-995c-4885-9630-20adb725f948)

(Doesn't show the raid level 500 in picture, but the cursed phalanx being awarded should be proof enough)

**Comment by nwjgit** [comment]
So the issue here is that only 1 CA can ever be given per quantity of thing i.e. 1 toa completion. The bot goes down the list of incomplete CA and if you roll the rng/meet the requirements it gives the ca and moves to the next quantity or in this case nothing since its only 1 quantity. This CA should really be moved into /ca claim or change its behavior since its fairly difficult to get. 

This is a band-aid fix but your best solution: get all the other CA first then do this CA last to guarantee the CA unlocks on a 500 completion.

**Comment by nwjgit** [comment]
Note to future self: Move this ca to /ca claim
