### ISSUE TITLE
Abyssal Cape

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#760]
## 🐛 Bug Report

Abyssal Cape does not get a bonus for Chambers of Xeric because it is not on the Wiki.

https://github.com/oldschoolgg/oldschoolbot/blob/6cc46b4c74a57d0d79f2c4cbd8caf88016703a1c/src/commands/Minion/raid.ts#L118-L140

**Comment by Lajnux** [comment]
Since we don't want to confuse the users that currently do raids that is coded based fully on the wiki guide, all custom items and better items like perfected gear won't be counted towards CoX at this point. Which also made a unique economy system.

In future CoX will be reworked so that it scales depending on equipped gear in a more dynamic way. This isn't a bug and intended feature.
