### ISSUE TITLE
me vs fishy 1v1 in general chat

### ISSUE THREAD

**Issue by wyattos** [oldschoolgg/oldschoolbot#849]
not gonna let the little cunt say dumb shit like this https://cdn.discordapp.com/attachments/744554460830760992/763590795185225778/unknown.png
when i have verifiable proof his bis is absolute dog shit (can literally copy paste every single part tearing his dumb ass theory apart)

"i still dont understand why he keps claiming stuff but never provide profs for it" LOL im literally offering that right now but your dumb ass wont accept the offer 

me vs fishy in general, we both pay a mod 1b each, whoever is correct takes 2b and the incorrect person has to shut the fuck up

**Comment by gc** [comment]
I've blocked you from interacting with any Oldschool.gg repo for 7 days. A singular more toxic thing like this, even if its just a bit toxic, whether its a private message someone shows me you sent, or a discord message, or a github issue, or anything anywhere, will make this ban permanent, and include a blacklist from the bot. Please grow up.

**Comment by fishytheretard** [comment]
personally i would not give any shits if i blacklisted, i just dont want fishy the retard trying to tell people how the bot works when he doesnt even know half of the code. never listen to any input he has on anything. he doesnt even play the fucking game
ps give the 1b you owe me away to the contributors not named alex

Stuff required for bis:
attack crush > zammy hasta crush, ie over 85
% melee strength > 60 % max, ie over 123 melee strength
kc >= 13 because of the natural log, at 13 kc "percentchanceofdeath" = 5.. then regardless of gear score you have the minimum chance of dying (5%)
```let percentChanceOfDeath = Math.floor(100 - (Math.log(kc) / Math.log(Math.sqrt(15))) * 50);

    // If they have 50% best gear, -25% chance of death.
    percentChanceOfDeath = Math.floor(percentChanceOfDeath - totalGearPercent / 2);

    // Chance of death cannot be over 90% or <2%.
    percentChanceOfDeath = Math.max(Math.min(percentChanceOfDeath, 90), 5);```

crush attack = 95.. combined with 13 kc you do the absolute maximum damage possible
```
    // Damage done starts off as being HP divided by user size.
    let damageDone = NIGHTMARES_HP / team.length;

    // Half it, to use a low damage amount as the base.
    damageDone /= 2;

    // If they have the BIS weapon, their damage is doubled.
    // e.g. 75% of of the best = 1.5x damage done.
    damageDone *= percentWeaponAttackCrush / 50;

    // Heavily punish them for having a weaker crush weapon than a zammy hasta.
    if (attackCrushStat < ZAM_HASTA_CRUSH) {
        damageDone /= 1.5;
    }

    // 20% less damage for very low KC
    if (kc < 10) {
        damageDone *= 0.8;
    }
```

now to use the minimum amount of food possible.. it checks your **SLASH DEFENSE** and **SLASH ATTACK**, and since no setup will provide meaningful slash attack without removing slash defense, and reducing crush attack (95 required) under 95, you focus on crush attack. so this means LITERALLY ANY weapon with 95 crush attack (big surprise thats a dwh) and gear with MAX SLASH DEFENSE is __**BIS**__
```
attackStyleToUse: GearSetupTypes.Melee,
attackStylesUsed: [GearStat.AttackSlash]

export const maxDefenceStats: { [key in DefenceGearStat]: number } = {
    [GearStat.DefenceCrush]: 505,
    [GearStat.DefenceMagic]: 253,
    [GearStat.DefenceRanged]: 542,
    [GearStat.DefenceSlash]: 521,
    [GearStat.DefenceStab]: 519
};

export const maxOffenceStats: { [key in OffenceGearStat]: number } = {
    [GearStat.AttackCrush]: 214,
    [GearStat.AttackMagic]: 177,
    [GearStat.AttackRanged]: 243,
    [GearStat.AttackSlash]: 182,
    [GearStat.AttackStab]: 177
};

const usersStyle = gearStats[inverseStyle];
const maxStyle = maxDefenceStats[inverseStyle]!;
const percent = floor(calcWhatPercent(usersStyle, maxStyle));
totalOffensivePercent += floor(
calcWhatPercent(gearStats[style], maxOffenceStats[style]));
```
get fucked turbo virgin, its almost like that picture playful sent you is actually bis fucking retard

**Comment by gc** [comment]
I've given both your github accounts permanent bans from Oldschool.gg repos and blacklisted you. You were given too many chances, this was your last chance. Bye.
