### ISSUE TITLE
+cl barrows bug 

### ISSUE THREAD

**Issue by imTurbo** [oldschoolgg/oldschoolbot#866]
## 🐛 Bug Report

![Screenshot_20201010-105749_Discord.jpg](https://user-images.githubusercontent.com/68685674/95659555-8204ae00-0ae7-11eb-9dd6-bf66206eb40e.jpg)

I get the error when I do +cl barrows

**Comment by tlbraams** [comment]
I think this issue is due to barrows having the monster id of just Dharok as is defined in oldschooljs: src/simulation/monsters/special/Barrows.ts.
It is defined **without** a loottable thus an error probably occurs when it is attempted to retrieve the items on line 41 in scr/commands/Minion/collectionlog.ts.
