### ISSUE TITLE
Bot won't return from Nightmare boss

### ISSUE THREAD

**Issue by Savakuda** [oldschoolgg/oldschoolbot#904]
My bot is stuck coming back from the Nightmare boss on a solo run. First time it has happened and it should have returned almost 15 minutes ago.

**Comment by gc** [comment]
There was a roughly 30-minute database rollback due to a bad bug, it should come back as normal. Keep in mind, this means that if you sent out a trip 30 minutes ago, right now it would be saying its only just been sent out,  and thats expected. Feel free to re-open this if you still think something is wrong.
