### ISSUE TITLE
BSO Item block list

### ISSUE THREAD

**Issue by adam55419** [oldschoolgg/oldschoolbot#912]
My suggestion is a way to block gaining items from drops/dailys by adding items to a block list eg;

=block bones *then you will never get bones from drops*

This way we can stop getting junk from dailies we dont want and crappy drops

**Comment by enriquevilla** [comment]
I think this could go on OSB too, though I propose an alternative solution, where instead of not getting the item, we can simply autosell it. Using something like

`+autosell bones`

should instead sell the bones automatically but still show them on the drops from the trip. Additionally, using

`+autosell`

we should see the list of items we have marked for this option.

**Comment by Lajnux** [comment]
this is a lot of code for very minor benefit, ppl that want clean banks should just clean them/sell the items they don't wanna keep. Lots of benefits been coded to make this process quicker. therefor closing this
